### ISSUE TITLE
I am having issue in cloning file in my pc. getting following error.

### ISSUE THREAD

**Issue by zaindroid** [Kojoley/atari-py#3]
Command "c:\users\pc\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\pc\\AppData\\Local\\Temp\\pip-req-build-6z3fwi12\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\pc\AppData\Local\Temp\pip-record-fk7dabl6\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\pc\AppData\Local\Temp\pip-req-build-6z3fwi12\

**Comment by zainey** [comment]
Command "c:\users\pc\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\pc\\AppData\\Local\\Temp\\pip-req-build-6z3fwi12\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\pc\AppData\Local\Temp\pip-record-fk7dabl6\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\pc\AppData\Local\Temp\pip-req-build-6z3fwi12\

**Comment by Kojoley** [comment]
Please provide the full log. This line does not contain any useful information about the actual error.

**Comment by Kojoley** [comment]
I'm closing this because of no response.

**Comment by zaindroid** [comment]
I had solved the issue by installing visual basic and it's depeendences

**Comment by Kojoley** [comment]
Great!
