### ISSUE TITLE
os 126

### ISSUE THREAD

**Issue by virdel** [Kojoley/atari-py#7]
When I use atari in pycharm, there is a error that is OSError: [WinError 126].
In ale_python_interface.py,
if os.name == 'posix':
    ale_lib = cdll.LoadLibrary(os.path.join(os.path.dirname(__file__),
                                            'ale_interface/libale_c.so'))
else:
    ale_lib = cdll.LoadLibrary(os.path.join(os.path.dirname(__file__),
                                            'ale_interface/ale_c.dll'))
The path "os.path.join(os.path.dirname(__file__),'ale_interface/ale_c.dll') " didn't exist.
Do you know how to solve?

**Comment by Kojoley** [comment]
You seems to be using the original library and not this fork as the code in your error message differs from https://github.com/Kojoley/atari-py/blob/cdb1e85fd90fe6a1e687f0a8bbc52410b733bbcb/atari_py/ale_python_interface.py#L14-L26

So, either you should open an issue on the original library bug tracker or install from this fork (instructions are on the main page https://github.com/Kojoley/atari-py) and then I probably could help you.

**Comment by virdel** [comment]
Thank you so much!
