### ISSUE TITLE
Unable to download file

### ISSUE THREAD

**Issue by trytodoit227** [Kojoley/atari-py#8]
This Website is very unstable, and it is definitely impossible to download the relevant files

**Comment by Kojoley** [comment]
Nothing I can do about that. It is also does not look like a global problem https://www.githubstatus.com/ https://downdetector.com/status/github/.

**Comment by trytodoit227** [comment]
That's OK. Thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Nikita Kniazev"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月2日(星期四) 凌晨0:00
收件人:&nbsp;"Kojoley/atari-py"<atari-py@noreply.github.com&gt;;
抄送:&nbsp;"奔跑的蜗牛"<1402892378@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Kojoley/atari-py] Unable to download file (#8)





 
Nothing I can do about that. It is also does not look like a global problem https://www.githubstatus.com/ https://downdetector.com/status/github/.

**Comment by Kojoley** [comment]
The license allows you to distribute copies, create a mirror. You may drop the links here.
