### ISSUE TITLE
Could not find a version that satisfies the requirement six

### ISSUE THREAD

**Issue by ouyangshan33** [Kojoley/atari-py#9]
Looking in links: https://github.com/Kojoley/atari-py/releases
Collecting atari_py
  Downloading https://github.com/Kojoley/atari-py/releases/download/1.2.1/atari_py-1.2.1-cp38-cp38-win_amd64.whl (683 kB)
     |████████████████████████████████| 683 kB 312 kB/s
Requirement already satisfied: numpy in e:\anaconda\envs\openai\lib\site-packages (from atari_py) (1.19.1)
ERROR: Could not find a version that satisfies the requirement six (from atari_py) (from versions: none)
ERROR: No matching distribution found for six (from atari_py)

I have met these two errors when trying to install it on window 10, could you please give some help?

**Comment by Kojoley** [comment]
You have not had installed `six` before installing this package, and I for some reason advertised the command with `--no-index` which disables PyPI repository usage. Anyway, I removed `six` dependency and binaries should appear soon.
